[editor]
scrolloff = 20
cursorline = true
rulers = [80]
line-number = "relative"
mouse = false
color-modes = true
true-color = true
auto-completion = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

# Not yet in stable release
# https://github.com/helix-editor/helix/pull/13133
# [editor.inline-blame]
# show = "cursor-line"

[keys.normal]
d = "delete_selection_noyank"
c = "change_selection_noyank"
A-d = "no_op"
A-c = "no_op"
C-j = "half_page_down"
C-k = "half_page_up"
