theme = "quiet_light"

[editor]
scrolloff = 20
cursorline = true
rulers = [80]
line-number = "relative"
color-modes = true
true-color = true
auto-completion = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

# Not yet in stable release
# https://github.com/helix-editor/helix/pull/13133
# [editor.inline-blame]
# show = "cursor-line"

[keys.normal]
d = "delete_selection_noyank"
c = "change_selection_noyank"
A-d = "no_op"
A-c = "no_op"
C-j = "half_page_down"
C-k = "half_page_up"
C-u = "kill_to_line_start"
G = "goto_last_line"
Cmd-c = "yank_main_selection_to_clipboard"
Cmd-x = ["yank_main_selection_to_clipboard", "delete_selection_noyank"]

[keys.normal.g]
j = "goto_last_line"
k = "goto_file_start"

[keys.select]
C-u = "kill_to_line_start"
G = "extend_to_last_line"
Cmd-c = "yank_main_selection_to_clipboard"
Cmd-x = ["yank_main_selection_to_clipboard", "delete_selection_noyank"]

[keys.select.g]
j = "extend_to_last_line"
k = "extend_to_file_start"

[keys.insert]
C-a = "goto_line_start"
C-e = "goto_line_end"
A-b = "move_prev_word_start"
A-f = "move_next_word_start"
C-left = "move_prev_sub_word_start"
C-right = "move_next_sub_word_end"
