[language-server.rust-analyzer]
config = { check = { command = "clippy", extraArgs = [
  "--",
  "--force-warn",
  "clippy::assigning-clones",
  "--force-warn",
  "clippy::ignore-without-reason",
  "--force-warn",
  "clippy::inline-always",
  "--force-warn",
  "clippy::should-panic-without-expect",
  "--force-warn",
  "clippy::bool-to-int-with-if",
  "--force-warn",
  "clippy::nonminimal-bool",
  "--force-warn",
  "clippy::overly-complex-bool-expr",
  "--force-warn",
  "clippy::borrow-as-ptr",
  "--force-warn",
  "clippy::cast-lossless",
  "--force-warn",
  "clippy::cast-ptr-alignment",
  "--force-warn",
  "clippy::ptr-as-ptr",
  "--force-warn",
  "clippy::ptr-cast-constness",
  "--force-warn",
  "clippy::ref-as-ptr",
  "--force-warn",
  "clippy::checked-conversions",
  "--force-warn",
  "clippy::collapsible-else-if",
  "--force-warn",
  "clippy::comparison-chain",
  "--force-warn",
  "clippy::copy-iterator",
  "--force-warn",
  "clippy::default-trait-access",
  "--force-warn",
  "clippy::explicit-deref-methods",
  "--force-warn",
  "clippy::ref-binding-to-reference",
  "--force-warn",
  "clippy::expl-impl-clone-on-copy",
  "--force-warn",
  "clippy::unsafe-derive-deserialize",
  "--force-warn",
  "clippy::doc-broken-link",
  "--force-warn",
  "clippy::doc-comment-double-space-linebreaks",
  "--force-warn",
  "clippy::doc-link-with-quotes",
  "--force-warn",
  "clippy::doc-markdown",
  "--force-warn",
  "clippy::duration-suboptimal-units",
  "--force-warn",
  "clippy::empty-enums",
  "--force-warn",
  "clippy::redundant-closure-for-method-calls",
  "--force-warn",
  "clippy::fn-params-excessive-bools",
  "--force-warn",
  "clippy::uninlined-format-args",
  "--force-warn",
  "clippy::unnecessary-debug-formatting",
  "--force-warn",
  "clippy::unnecessary-trailing-comma",
  "--force-warn",
  "clippy::format-push-string",
  "--force-warn",
  "clippy::must-use-candidate",
  "--force-warn",
  "clippy::ref-option",
  "--force-warn",
  "clippy::if-not-else",
  "--force-warn",
  "clippy::same-functions-in-if-condition",
  "--force-warn",
  "clippy::ignored-unit-patterns",
  "--force-warn",
  "clippy::implicit-hasher",
  "--force-warn",
  "clippy::inconsistent-struct-constructor",
  "--force-warn",
  "clippy::index-refutable-slice",
  "--force-warn",
  "clippy::maybe-infinite-iter",
  "--force-warn",
  "clippy::struct-field-names",
  "--force-warn",
  "clippy::items-after-statements",
  "--force-warn",
  "clippy::iter-not-returning-iterator",
  "--force-warn",
  "clippy::into-iter-without-iter",
  "--force-warn",
  "clippy::iter-without-into-iter",
  "--force-warn",
  "clippy::large-futures",
  "--force-warn",
  "clippy::large-stack-arrays",
  "--force-warn",
  "clippy::elidable-lifetime-names",
  "--force-warn",
  "clippy::large-digit-groups",
  "--force-warn",
  "clippy::unreadable-literal",
  "--force-warn",
  "clippy::explicit-into-iter-loop",
  "--force-warn",
  "clippy::explicit-iter-loop",
  "--force-warn",
  "clippy::macro-use-imports",
  "--force-warn",
  "clippy::manual-assert",
  "--force-warn",
  "clippy::manual-assert-eq",
  "--force-warn",
  "clippy::manual-ilog2",
  "--force-warn",
  "clippy::manual-is-power-of-two",
  "--force-warn",
  "clippy::manual-let-else",
  "--force-warn",
  "clippy::manual-string-new",
  "--force-warn",
  "clippy::match-bool",
  "--force-warn",
  "clippy::match-same-arms",
  "--force-warn",
  "clippy::match-wild-err-arm",
  "--force-warn",
  "clippy::match-wildcard-for-single-variants",
  "--force-warn",
  "clippy::single-match-else",
  "--force-warn",
  "clippy::case-sensitive-file-extension-comparisons",
  "--force-warn",
  "clippy::cloned-instead-of-copied",
  "--force-warn",
  "clippy::filter-map-next",
  "--force-warn",
  "clippy::flat-map-option",
  "--force-warn",
  "clippy::format-collect",
  "--force-warn",
  "clippy::from-iter-instead-of-collect",
  "--force-warn",
  "clippy::implicit-clone",
  "--force-warn",
  "clippy::inefficient-to-string",
  "--force-warn",
  "clippy::ip-constant",
  "--force-warn",
  "clippy::iter-filter-is-ok",
  "--force-warn",
  "clippy::iter-filter-is-some",
  "--force-warn",
  "clippy::manual-is-variant-and",
  "--force-warn",
  "clippy::map-unwrap-or",
  "--force-warn",
  "clippy::naive-bytecount",
  "--force-warn",
  "clippy::option-as-ref-cloned",
  "--force-warn",
  "clippy::ptr-offset-by-literal",
  "--force-warn",
  "clippy::stable-sort-primitive",
  "--force-warn",
  "clippy::str-split-at-newline",
  "--force-warn",
  "clippy::unnecessary-join",
  "--force-warn",
  "clippy::used-underscore-binding",
  "--force-warn",
  "clippy::used-underscore-items",
  "--force-warn",
  "clippy::mismatching-type-param-order",
  "--force-warn",
  "clippy::missing-fields-in-debug",
  "--force-warn",
  "clippy::mut-mut",
  "--force-warn",
  "clippy::needless-continue",
  "--force-warn",
  "clippy::needless-for-each",
  "--force-warn",
  "clippy::needless-pass-by-value",
  "--force-warn",
  "clippy::no-effect-underscore-binding",
  "--force-warn",
  "clippy::no-mangle-with-rust-abi",
  "--force-warn",
  "clippy::many-single-char-names",
  "--force-warn",
  "clippy::non-std-lazy-statics",
  "--force-warn",
  "clippy::self-only-used-in-recursion",
  "--force-warn",
  "clippy::decimal-bitwise-operands",
  "--force-warn",
  "clippy::float-cmp",
  "--force-warn",
  "clippy::invalid-upcast-comparisons",
  "--force-warn",
  "clippy::manual-midpoint",
  "--force-warn",
  "clippy::needless-bitwise-bool",
  "--force-warn",
  "clippy::verbose-bit-mask",
  "--force-warn",
  "clippy::large-types-passed-by-value",
  "--force-warn",
  "clippy::trivially-copy-pass-by-ref",
  "--force-warn",
  "clippy::pub-underscore-fields",
  "--force-warn",
  "clippy::range-minus-one",
  "--force-warn",
  "clippy::range-plus-one",
  "--force-warn",
  "clippy::needless-raw-string-hashes",
  "--force-warn",
  "clippy::redundant-else",
  "--force-warn",
  "clippy::ref-option-ref",
  "--force-warn",
  "clippy::return-self-not-must-use",
  "--force-warn",
  "clippy::same-length-and-capacity",
  "--force-warn",
  "clippy::semicolon-if-nothing-returned",
  "--force-warn",
  "clippy::single-char-pattern",
  "--force-warn",
  "clippy::string-add-assign",
  "--force-warn",
  "clippy::manual-instant-elapsed",
  "--force-warn",
  "clippy::unchecked-time-subtraction",
  "--force-warn",
  "clippy::transmute-ptr-to-ptr",
  "--force-warn",
  "clippy::linkedlist",
  "--force-warn",
  "clippy::option-option",
  "--force-warn",
  "clippy::unicode-not-nfc",
  "--force-warn",
  "clippy::unnecessary-box-returns",
  "--force-warn",
  "clippy::unnecessary-literal-bound",
  "--force-warn",
  "clippy::unnecessary-semicolon",
  "--force-warn",
  "clippy::unnecessary-wraps",
  "--force-warn",
  "clippy::unnested-or-patterns",
  "--force-warn",
  "clippy::unused-async",
  "--force-warn",
  "clippy::unused-self",
  "--force-warn",
  "clippy::enum-glob-use",
  "--force-warn",
  "clippy::wildcard-imports",
  "--force-warn",
  "clippy::zero-sized-map-values",
  "-Dwarnings",
] }, diagnostics = { styleLints = { enable = true } }, inlayHints = { closureStyle = "rust_analyzer", typeHints = { hideNamedConstructor = true, hideClosureInitialization = true }, expressionAdjustmentHints = { enable = "reborrow" }, closureCaptureHints = { enable = true }, closingBraceHints = { minLines = 40 } }, semanticHighlighting = { punctuation = { enable = true, specialization = { enable = true }, separate = { macro = { bang = true } } }, operator = { specialization = { enable = true } } }, lens = { references = { adt = { enable = true }, enumVariant = { enable = true }, method = { enable = true }, trait = { enable = true } } } }

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.vscode-eslint-language-server]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.vscode-eslint-language-server.config]
validate = "on"
experimental = { useFlatConfig = true }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""

[language-server.flint]
command = "fnm"
args = ["exec", "--using=default", "--", "npx", "flint", "lsp"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.sourcery]
command = "sourcery"
args = ["lsp"]
config = { token = "SOURCERY_TOKEN", extension_version = "helix.lsp", editor_version = "helix" }

[language-server.vscode-json-language-server.config.json.schemas]
"https://json.schemastore.org/package.json" = ["package.json"]
"https://json.schemastore.org/tsconfig.json" = [
  "tsconfig.json",
  "tsconfig.*.json",
]
"https://json.schemastore.org/biome.json" = ["biome.json", "biome.jsonc"]
"https://json.schemastore.org/eslintrc.json" = [".eslintrc", ".eslintrc.json"]
"https://json.schemastore.org/pyrightconfig.json" = ["pyrightconfig.json"]

[language-server.yaml-language-server.config.yaml]
schemas = { "https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.yml" }
validation = true
completion = true

[language-server.stylelint-lsp]
command = "stylelint-lsp"
args = ["--stdio"]

[language-server.vscode-html-language-server.config]
provideFormatter = true
css = { validate = true, lint = { validProperties = [] } }

[language-server.vscode-css-language-server.config]
provideFormatter = true
css = { validate = true, lint = { validProperties = [] } }
scss = { validate = true, lint = { validProperties = [] } }
less = { validate = true, lint = { validProperties = [] } }

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  { name = "flint", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "sourcery", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "biome", except-features = ["format"] },
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  { name = "flint", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "sourcery", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "biome", except-features = ["format"] },
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  { name = "flint", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "sourcery", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "biome", except-features = ["format"] },
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  { name = "flint", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "sourcery", only-features = [
    "diagnostics",
    "code-action",
  ] },
  { name = "biome", except-features = ["format"] },
]


[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "basedpyright", except-features = [
    "format",
  ] },
  "ruff",
  { name = "sourcery", only-features = [
    "diagnostics",
    "code-action",
  ] },
]

[[language]]
name = "json"
language-id = "jsonc"

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2"] }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "markdownlint-cli2", args = ["--fix"] }
language-servers = ["marksman", "rumdl"]

[[language]]
name = "css"
language-servers = [
  "vscode-css-language-server",
  { name = "stylelint-lsp", only-features = ["diagnostics"] },
]

[[language]]
name = "scss"
language-servers = [
  "vscode-css-language-server",
  { name = "stylelint-lsp", only-features = ["diagnostics"] },
]

[[language]]
name = "html"
indent = { tab-width = 4, unit = "    " }
